### ISSUE TITLE
Update MongoDriver to 2.0

### ISSUE THREAD

**Issue by andreabalducci** [NEventStore/NEventStore.Persistence.MongoDB#19]
http://www.nuget.org/packages/MongoDB.Driver/2.0.0-beta1

**Comment by hnafar** [comment]
I am working on implementing this with mongo driver 2.0. MongoDb C# driver v2 has a large number of breaking changes. NEventStore.Persistence.MongoDB is mostly affected by changes in dictionary serialization, see https://groups.google.com/forum/#!topic/mongodb-user/CDUTFoFF4FU and https://groups.google.com/forum/#!topic/mongodb-user/nlBxnhR-BWg which cause the acceptance test when_a_commit_header_has_a_name_that_contains_a_period to fail. you can set CheckElementNames = false, but this seems to be very unsafe. custom escaping dictionary names is another option, but it might affect reading commits written by an older version.

**Comment by andreabalducci** [comment]
I know, I'm planning this for vNext with async support

**Comment by andreabalducci** [comment]
the main issue is framework support, we need to move to .Net 4.5 so it's not an implementation for this version of NEventStore

**Comment by MikeEast** [comment]
Any updates on this?

**Comment by andreabalducci** [comment]
@hnafar want to help? new CI server is up & running so we could upgrade mongo driver for 5.3 (if we can avoid breaking schema changes, otherwise is for v6)

**Comment by andreabalducci** [comment]
up on branch v.5.3, needs more testing & refactoring.
all tests are green

**Comment by davideicardi** [comment]
Do you think that v.5.3 is already usable on production?
Any plan for an official nuget package? Eventually I'm available to help...

**Comment by andreabalducci** [comment]
Will be released by the end of November, you can find the nuget package on our CI myget feed.
We plan to switch to this release on our internal projects in the next 2 weeks.

**Comment by davideicardi** [comment]
Thank you Andrea, can you point me to the right myget feed? 
I have found 
https://www.myget.org/feed/neventstore-ci/package/nuget/NEventStore.Persistence.MongoDB
but here I cannot find the correct library compiled with 2.0 driver.

**Comment by davideicardi** [comment]
For now I have published nuget package from my private build at https://www.myget.org/feed/webplu/package/nuget/Webplu-NEventStore.Persistence.MongoDB

When official nuget is available please let me know. In the meantime I will try it with our solution.

**Comment by andreabalducci** [comment]
did some testing this morning, driver v2 is not production ready imho, we have to wait for 2.2
see https://github.com/andreabalducci/mongo-bench

**Comment by ZodiacZA** [comment]
Very interested in this feature. Currently haven't compatibility issues with the old driver and the new one used by other packages.

**Comment by andreabalducci** [comment]
all tests are green, next week code we'll do a code review and merge to develop.
https://github.com/NEventStore/NEventStore.Persistence.MongoDB/commits/feature/mongodb-driver-2

**Comment by andreabalducci** [comment]
Now Headers are serialized as ArrayOfArrays

**Comment by ZodiacZA** [comment]
Great seeing progress! Looking forward to this feature.

**Comment by AGiorgetti** [comment]
The change in how Headers dictionary is serialized lead to a bug when there are custom serialization conventions enabled in mongodb, see this issue: #31

**Comment by AGiorgetti** [comment]
I looked at the code of the old mongo-csharp-driver, it turns out that dictionary serialization worked quite differently from the actual driver: the previous one was 'adaptive' it was able to chose which kind of serialization to use (Document or ArrayOfArrays) looking at the dictionary keys, so you could end up with 'mixed serialization scheme' for your dictionaries.

The new driver removed support for this dynamic serialization/deserialization mode, so we need to enforce a standard serialization here (and as Andrea already did 'ArrayOfArrays' seems the more logical choice).

This will result in a major breaking change as people will need to adapt their current Commit collection to conform to the newly chosen standard.

**Comment by AGiorgetti** [comment]
More details about this can be found on the following links:
https://jira.mongodb.org/browse/CSHARP-939
https://jira.mongodb.org/browse/CSHARP-1165

We have differents options here:
- pickup one serialization scheme (ArrayOfArrays) and have people adapt their databases.
- allow the driver to be configurable so the user can specify which kind of serialization to use for the dictionaries collection (I can do a PR for this).
- rework how the driver does the serialization: instead of building the BSonDocument ourselves we can provide a class and let the user configure the serialization scheme he prefers using the standard mongodb mapping API. This will add flexibility, but it's also the option that can cause more confusion (there will be interactions with other conventions the user can change, see #31).

**Comment by AGiorgetti** [comment]
Dictionary serialization and mapping customization through the new MongoCommit class are now sorted, you can just use the standard MongoDB mapping infrastructure to decide how to serialize and persist each commit.

A sample for this can be found here: https://github.com/NEventStore/NEventStore.Persistence.MongoDB/blob/develop/src/NEventStore.Persistence.MongoDB.Tests/AcceptanceTests/MongoCommitCustomSerializationTests.cs

I think we can close this issue.

**Comment by ChrisMcKee** [comment]
Hi, is there any reason this is going to wait for v6 rather than as part of v5.x? 
The 1.10/11 driver isn't compatible with Mongo after 3.2 and its looking like 3.4 will be the first version to even come close to passing jepson https://jepsen.io/analyses/mongodb-3-4-0-rc3

**Comment by andreabalducci** [comment]
we have v6 in production from months, using the myget feed. V6 will be released in March with a minor update on SqlSchema, you can gram V6 from myget or sources and go live.

**Comment by ChrisMcKee** [comment]
@andreabalducci cool, thanks! Also thanks again, that was a bloody fast reply 👍

**Comment by garie** [comment]
Is this ever going to be released with nuget.org?

**Comment by andreabalducci** [comment]
yes, we've decided to complete .netstandard2 port (currently in branch) and release it.
Meanwhile we could release as -pre packages, after all has been used in production for months (not the same for the other providers).

**Comment by garie** [comment]
It would be super awesome if a prerelease package was out, we would really like to upgrade so that we can get a bug fix from mongo 2.

**Comment by andreabalducci** [comment]
Will be pushed next week, just the time for some checks with the team.
We spent last few weeks in a full async rewrite (we are moving our project on the new evenstore) but we agreed on releasing NES v6 on .netstandard 2 in september.

**Comment by AGiorgetti** [comment]
Driver has been updated to 2.7.x
